apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-analyzer
  template:
    metadata:
      labels:
        app: log-analyzer
    spec:
      containers:
        - name: log-analyzer
          # Make sure this matches whatever you name the image when you build it!
          image: danish/log-analyzer:latest 
          imagePullPolicy: IfNotPresent 
          env:
            - name: REDIS_HOST
              value: "redis"
            - name: REDIS_PORT
              value: "6379"